### ISSUE TITLE
[ Feature Request ] Add Qt UI

### ISSUE THREAD

**Issue by mcirsta** [rhaidiz/yves#1]
[broxy](https://github.com/rhaidiz/broxy) Has a nice QT UI. Any chance this will be implemented here. I'm really looking for something like this and I am willing to help. My first idea was to just try and work on Broxy.

**Comment by rhaidiz** [comment]
The idea, assuming I actually start working on it, is to keep yves as a standalone library with mitm features and write the interface natively. The QT library I used in broxy was to experiment, the library itself was very impressive work but honestly I've always found it to be a little hacky.
